eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://clients-db:5432/clients
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090