eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: client
            uri: lb://client
            predicates:
              - Path=/api/client/**
          - id: account
            uri: lb://account
            predicates:
              - Path=/api/**