eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8222

spring:
  cloud:
    gateway:
      routes:
          - id: client
            uri: client
            predicates:
              - Path=/api/client/**
          - id: account
            uri: account
            predicates:
              - Path=/api/**